---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "cps-influxdb"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cps-influxdb"
  serviceName: influxdb-service
  template:
    metadata:
      labels:
        app: "cps-influxdb"
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: influxdb-disk-claim
      containers:
        - env:
          image: "influxdb:2.0.7"
          imagePullPolicy: "IfNotPresent"
          name: "cps-influxdb"
          ports:
            - containerPort: 8086
          volumeMounts:
            - mountPath: /var/lib/influxdb2
              name: data
          env:
          - name: INFLUXD_BOLT_PATH
            value: "/var/lib/influxdb2/engine/data/influxd.bolt"
          - name: INFLUXD_STORAGE_CACHE_SNAPSHOT_WRITE_COLD_DURATION
            value: "5s"
          - name: INFLUXDB_HTTP_AUTH_ENABLED
            value: "true"
          - name: DOCKER_INFLUXDB_INIT_MODE
            value: "setup"
          - name: DOCKER_INFLUXDB_INIT_USERNAME
            value: "USERNAME"
          - name: DOCKER_INFLUXDB_INIT_PASSWORD
            value: "PASSWORD"
          - name: DOCKER_INFLUXDB_INIT_ORG
            value: "CPS_HF"
          - name: DOCKER_INFLUXDB_INIT_BUCKET
            value: "MEASUREMENTS"
      nodeSelector:
        server: edge
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influxdb-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
      nodePort: 31761
  selector:
    app: cps-influxdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-disk-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
     storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-disk
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "~/test_volume"