---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cps-influxdb-client"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cps-influxdb-client"
  template:
    metadata:
      labels:
        app: "cps-influxdb-client"
    spec:
      containers:
        - env:
          image: "nandorlengyel/cps_influxdb_client:latest"
          imagePullPolicy: "Always"
          name: "cps-influxdb-client"
      nodeSelector:
        server: edge
