---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cps-prediction-system"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cps-prediction-system"
  template:
    metadata:
      labels:
        app: "cps-prediction-system"
    spec:
      containers:
        - env:
          image: "nandorlengyel/cps_prediction_system:latest"
          imagePullPolicy: "Always"
          name: "cps-prediction-system"
          env:
          - name: INFLUXDB_V2_TOKEN
            value: "COh369Rkk5vK4ijGCi1cwgUCxyI9jCLlWMP7EEcsPS7zyMHnPcfZRSs6sgtWbJEir4sztTIPhzuOeR2jHgekDQ=="
          - name: INFLUXDB_V2_URL
            value: "http://influxdb-service:8086"
          - name: INFLUXDB_V2_ORG
            value: "CPS_HF"
      # set to cloud
      nodeSelector:
        server: edge
