---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cps-current-data-logger"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cps-current-data-logger"
  template:
    metadata:
      labels:
        app: "cps-current-data-logger"
    spec:
      containers:
        - env:
          image: "nandorlengyel/cps_current_data_logger:latest"
          imagePullPolicy: "Always"
          name: "cps-current-data-logger"
          env:
          - name: PICO_IP
            value: "169.254.53.98"
      nodeSelector:
        # TODO: uncomment next line
        #sensor: picolog-cm3
        sensor: photoresistor
