---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cps-influxdb"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cps-influxdb"
  template:
    metadata:
      labels:
        app: "cps-influxdb"
    spec:
      containers:
        - env:
          image: "influxdb:2.0.7"
          imagePullPolicy: "IfNotPresent"
          name: "cps-influxdb"
      nodeSelector:
        server: edge
